In [1]:
import pandas as pd
df = pd.read_csv("../data/processed/clean_supply_chain.csv")
df.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_state,order_status,product_card_id,product_category_id,product_image,product_name,product_price,product_status,shipping_date_dateorders,shipping_mode
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,...,Java Occidental,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,...,Rajastán,PENDING,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,...,Rajastán,CLOSED,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,...,Queensland,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,...,Queensland,PENDING_PAYMENT,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 51 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   type                         180519 non-null  str
 1   days_for_shipping_real       180519 non-null  int64
 2   days_for_shipment_scheduled  180519 non-null  int64
 3   benefit_per_order            180519 non-null  float64
 4   sales_per_customer           180519 non-null  float64
 5   delivery_status              180519 non-null  str
 6   late_delivery_risk           180519 non-null  int64
 7   category_id                  180519 non-null  int64
 8   category_name                180519 non-null  str
 9   customer_city                180519 non-null  str
 10  customer_country             180519 non-null  str
 11  customer_email               180519 non-null  str
 12  customer_fname               180519 non-null  str
 13  customer_id                  180519 non-null  int64
 14  customer_lname               180519 non-null  str
 15  customer_password            180519 non-null  str
 16  customer_segment             180519 non-null  str
 17  customer_state               180519 non-null  str
 18  customer_street              180519 non-null  str
 19  customer_zipcode             180519 non-null  float64
 20  department_id                180519 non-null  int64
 21  department_name              180519 non-null  str
 22  latitude                     180519 non-null  float64
 23  longitude                    180519 non-null  float64
 24  market                       180519 non-null  str
 25  order_city                   180519 non-null  str
 26  order_country                180519 non-null  str
 27  order_customer_id            180519 non-null  int64
 28  order_date_dateorders        180519 non-null  str
 29  order_id                     180519 non-null  int64
 30  order_item_cardprod_id       180519 non-null  int64
 31  order_item_discount          180519 non-null  float64
 32  order_item_discount_rate     180519 non-null  float64
 33  order_item_id                180519 non-null  int64
 34  order_item_product_price     180519 non-null  float64
 35  order_item_profit_ratio      180519 non-null  float64
 36  order_item_quantity          180519 non-null  int64
 37  sales                        180519 non-null  float64
 38  order_item_total             180519 non-null  float64
 39  order_profit_per_order       180519 non-null  float64
 40  order_region                 180519 non-null  str
 41  order_state                  180519 non-null  str
 42  order_status                 180519 non-null  str
 43  product_card_id              180519 non-null  int64
 44  product_category_id          180519 non-null  int64
 45  product_image                180519 non-null  str
 46  product_name                 180519 non-null  str
 47  product_price                180519 non-null  float64
 48  product_status               180519 non-null  int64
 49  shipping_date_dateorders     180519 non-null  str
 50  shipping_mode                180519 non-null  str
dtypes: float64(13), int64(14), str(24)
memory usage: 127.1 MB

In [6]:
df.shape

(180519, 51)

In [3]:
df.columns

Index(['type', 'days_for_shipping_real', 'days_for_shipment_scheduled',
       'benefit_per_order', 'sales_per_customer', 'delivery_status',
       'late_delivery_risk', 'category_id', 'category_name', 'customer_city',
       'customer_country', 'customer_email', 'customer_fname', 'customer_id',
       'customer_lname', 'customer_password', 'customer_segment',
       'customer_state', 'customer_street', 'customer_zipcode',
       'department_id', 'department_name', 'latitude', 'longitude', 'market',
       'order_city', 'order_country', 'order_customer_id',
       'order_date_dateorders', 'order_id', 'order_item_cardprod_id',
       'order_item_discount', 'order_item_discount_rate', 'order_item_id',
       'order_item_product_price', 'order_item_profit_ratio',
       'order_item_quantity', 'sales', 'order_item_total',
       'order_profit_per_order', 'order_region', 'order_state', 'order_status',
       'product_card_id', 'product_category_id', 'product_image',
       'product_name', 'product_price', 'product_status',
       'shipping_date_dateorders', 'shipping_mode'],
      dtype='str')

In [4]:
df.describe()

,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,late_delivery_risk,category_id,customer_id,customer_zipcode,department_id,latitude,...,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,product_card_id,product_category_id,product_price,product_status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107607,0.548291,31.851451,6691.379495,35920.852021,5.443460,29.719955,...,141.232547,0.120647,2.127638,203.772092,183.107607,21.974989,692.509764,31.851451,141.232547,0.0
std,1.623722,1.374449,104.433526,120.043668,0.497664,15.640064,4162.918106,37542.209723,1.629246,9.813646,...,139.732489,0.466796,1.453451,132.273075,120.043668,104.433526,336.446807,15.640064,139.732489,0.0
min,0.000000,0.000000,-4274.980000,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.980000,19.000000,2.000000,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.380000,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,50.000000,0.080000,1.000000,119.980000,104.380000,7.000000,403.000000,18.000000,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990000,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,59.990000,0.270000,1.000000,199.920000,163.990000,31.520000,627.000000,29.000000,59.990000,0.0
75%,5.000000,4.000000,64.800000,247.400000,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,199.990000,0.360000,3.000000,299.950000,247.400000,64.800000,1004.000000,45.000000,199.990000,0.0
max,6.000000,4.000000,911.800000,1939.990000,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,1999.990000,0.500000,5.000000,1999.990000,1939.990000,911.800000,1363.000000,76.000000,1999.990000,0.0

In [5]:
df.isnull().sum()

type                           0
days_for_shipping_real         0
days_for_shipment_scheduled    0
benefit_per_order              0
sales_per_customer             0
delivery_status                0
late_delivery_risk             0
category_id                    0
category_name                  0
customer_city                  0
customer_country               0
customer_email                 0
customer_fname                 0
customer_id                    0
customer_lname                 0
customer_password              0
customer_segment               0
customer_state                 0
customer_street                0
customer_zipcode               0
department_id                  0
department_name                0
latitude                       0
longitude                      0
market                         0
order_city                     0
order_country                  0
order_customer_id              0
order_date_dateorders          0
order_id                       0
order_item_cardprod_id         0
order_item_discount            0
order_item_discount_rate       0
order_item_id                  0
order_item_product_price       0
order_item_profit_ratio        0
order_item_quantity            0
sales                          0
order_item_total               0
order_profit_per_order         0
order_region                   0
order_state                    0
order_status                   0
product_card_id                0
product_category_id            0
product_image                  0
product_name                   0
product_price                  0
product_status                 0
shipping_date_dateorders       0
shipping_mode                  0
dtype: int64

# Model Development

## Load Processed Dataset

The cleaned supply chain dataset is loaded from the processed folder for machine learning.

## Dataset Overview

The following cells inspect the size, columns, and data types.

In [8]:
## Exploratory Data Analysis

In [9]:
#Checking target distribution-
df["late_delivery_risk"].value_counts()

late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [10]:
df["late_delivery_risk"].value_counts(normalize=True) * 100

late_delivery_risk
1    54.829132
0    45.170868
Name: proportion, dtype: float64

In [11]:
#checking missing values
df.isnull().sum().sort_values(ascending=False)

type                           0
days_for_shipping_real         0
days_for_shipment_scheduled    0
benefit_per_order              0
sales_per_customer             0
delivery_status                0
late_delivery_risk             0
category_id                    0
category_name                  0
customer_city                  0
customer_country               0
customer_email                 0
customer_fname                 0
customer_id                    0
customer_lname                 0
customer_password              0
customer_segment               0
customer_state                 0
customer_street                0
customer_zipcode               0
department_id                  0
department_name                0
latitude                       0
longitude                      0
market                         0
order_city                     0
order_country                  0
order_customer_id              0
order_date_dateorders          0
order_id                       0
order_item_cardprod_id         0
order_item_discount            0
order_item_discount_rate       0
order_item_id                  0
order_item_product_price       0
order_item_profit_ratio        0
order_item_quantity            0
sales                          0
order_item_total               0
order_profit_per_order         0
order_region                   0
order_state                    0
order_status                   0
product_card_id                0
product_category_id            0
product_image                  0
product_name                   0
product_price                  0
product_status                 0
shipping_date_dateorders       0
shipping_mode                  0
dtype: int64

In [12]:
#Coorelations
numeric_df = df.select_dtypes(include=["number"])

numeric_df.corr()["late_delivery_risk"].sort_values(ascending=False)

late_delivery_risk             1.000000
days_for_shipping_real         0.401415
customer_zipcode               0.003151
category_id                    0.001752
product_category_id            0.001752
order_item_cardprod_id         0.001490
product_card_id                0.001490
order_customer_id              0.001484
customer_id                    0.001484
department_id                  0.001077
latitude                       0.000679
order_item_discount_rate       0.000404
order_item_quantity           -0.000139
order_item_discount           -0.000750
order_id                      -0.001293
order_item_id                 -0.001376
longitude                     -0.001915
order_item_product_price      -0.002175
product_price                 -0.002175
order_item_profit_ratio       -0.002316
sales                         -0.003564
benefit_per_order             -0.003727
order_profit_per_order        -0.003727
order_item_total              -0.003791
sales_per_customer            -0.003791
days_for_shipment_scheduled   -0.369352
product_status                      NaN
Name: late_delivery_risk, dtype: float64

In [13]:
#Removing unnecessary columns
columns_to_drop = [
    "customer_email",
    "customer_password",
    "customer_fname",
    "customer_lname",
    "customer_street",
    "product_image",
    "order_id",
    "customer_id",
    "order_customer_id",
    "order_item_id",
    "product_card_id"
]

df = df.drop(columns=columns_to_drop)

In [14]:
#Separate target and feature variable
X = df.drop("late_delivery_risk", axis=1)
y = df["late_delivery_risk"]

In [15]:
print(X.shape)
print(y.shape)

(180519, 39)
(180519,)

In [16]:
#Categorical columns
X.select_dtypes(include="object").columns

C:\Users\muska\AppData\Local\Temp\ipykernel_6436\3535082521.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X.select_dtypes(include="object").columns

Index(['type', 'delivery_status', 'category_name', 'customer_city',
       'customer_country', 'customer_segment', 'customer_state',
       'department_name', 'market', 'order_city', 'order_country',
       'order_date_dateorders', 'order_region', 'order_state', 'order_status',
       'product_name', 'shipping_date_dateorders', 'shipping_mode'],
      dtype='str')

In [17]:
X = X.drop(columns=["delivery_status"])

In [18]:
X["order_date_dateorders"] = pd.to_datetime(X["order_date_dateorders"])

X["shipping_date_dateorders"] = pd.to_datetime(
    X["shipping_date_dateorders"]
)

In [19]:
X["order_year"] = X["order_date_dateorders"].dt.year
X["order_month"] = X["order_date_dateorders"].dt.month
X["order_day"] = X["order_date_dateorders"].dt.day
X["order_weekday"] = X["order_date_dateorders"].dt.dayofweek

In [20]:
X["shipping_year"] = X["shipping_date_dateorders"].dt.year
X["shipping_month"] = X["shipping_date_dateorders"].dt.month
X["shipping_day"] = X["shipping_date_dateorders"].dt.day

In [21]:
X = X.drop(
    columns=[
        "order_date_dateorders",
        "shipping_date_dateorders"
    ]
)

In [22]:
X.select_dtypes(include=["object", "string"]).columns

Index(['type', 'category_name', 'customer_city', 'customer_country',
       'customer_segment', 'customer_state', 'department_name', 'market',
       'order_city', 'order_country', 'order_region', 'order_state',
       'order_status', 'product_name', 'shipping_mode'],
      dtype='str')

In [23]:
X.nunique().sort_values(ascending=False)

benefit_per_order              21998
order_profit_per_order         21998
latitude                       11250
longitude                       4487
order_city                      3597
sales_per_customer              2927
order_item_total                2927
order_state                     1089
order_item_discount             1017
customer_zipcode                 995
customer_city                    563
sales                            193
order_country                    164
order_item_profit_ratio          162
order_item_cardprod_id           118
product_name                     118
product_price                     75
order_item_product_price          75
category_id                       51
product_category_id               51
category_name                     50
customer_state                    46
shipping_day                      31
order_day                         31
order_region                      23
order_item_discount_rate          18
shipping_month                    12
order_month                       12
department_name                   11
department_id                     11
order_status                       9
days_for_shipping_real             7
order_weekday                      7
order_item_quantity                5
market                             5
shipping_mode                      4
order_year                         4
type                               4
days_for_shipment_scheduled        4
shipping_year                      4
customer_segment                   3
customer_country                   2
product_status                     1
dtype: int64

In [24]:
df["delivery_status"].value_counts()

delivery_status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

In [27]:
#Drop high cardinality columns
columns_to_drop = [
    "order_city",
    "customer_city",
    "order_state",
    "customer_zipcode"
]

X = X.drop(columns=columns_to_drop, errors="ignore")

In [28]:
X.select_dtypes(include=["object", "string"]).columns

Index(['type', 'category_name', 'customer_country', 'customer_segment',
       'customer_state', 'department_name', 'market', 'order_country',
       'order_region', 'order_status', 'product_name', 'shipping_mode'],
      dtype='str')

In [29]:
X.select_dtypes(include=["object", "string"]).nunique()

type                  4
category_name        50
customer_country      2
customer_segment      3
customer_state       46
department_name      11
market                5
order_country       164
order_region         23
order_status          9
product_name        118
shipping_mode         4
dtype: int64

In [30]:
df["order_status"].value_counts()

order_status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

## Encoding Categorical Variables

In [31]:
X = pd.get_dummies(
    X,
    columns=X.select_dtypes(include=["object", "string"]).columns,
    drop_first=True
)

In [32]:
X.shape

(180519, 454)

In [33]:
X.head()

,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,category_id,department_id,latitude,longitude,order_item_cardprod_id,order_item_discount,...,product_name_Yakima DoubleDown Ace Hitch Mount 4-Bike Rack,product_name_adidas Brazuca 2014 Official Match Ball,product_name_adidas Kids' F5 Messi FG Soccer Cleat,product_name_adidas Men's F10 Messi TRX FG Soccer Cleat,product_name_adidas Men's Germany Black Crest Away Tee,product_name_adidas Youth Germany Black/Red Away Match Soc,product_name_insta-bed Neverflat Air Mattress,shipping_mode_Same Day,shipping_mode_Second Class,shipping_mode_Standard Class
0,3,4,91.25,314.64,73,2,18.251453,-66.037056,1360,13.11,...,False,False,False,False,False,False,False,False,False,True
1,5,4,-249.09,311.36,73,2,18.279451,-66.037060,1360,16.39,...,False,False,False,False,False,False,False,False,False,True
2,4,4,-247.78,309.72,73,2,37.292233,-121.881280,1360,18.03,...,False,False,False,False,False,False,False,False,False,True
3,3,4,22.86,304.81,73,2,34.125946,-118.291016,1360,22.94,...,False,False,False,False,False,False,False,False,False,True
4,2,4,134.21,298.25,73,2,18.253769,-66.037050,1360,29.50,...,False,False,False,False,False,False,False,False,False,True