In [1]:
import pandas as pd

C:\Users\sruth\AppData\Local\Temp\ipykernel_8328\2035458946.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv("../data/processed/clean_supply_chain.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (180519, 51)

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_state,order_status,product_card_id,product_category_id,product_image,product_name,product_price,product_status,shipping_date_dateorders,shipping_mode
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,...,Java Occidental,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,...,Rajastán,PENDING,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,...,Rajastán,CLOSED,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,...,Queensland,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,...,Queensland,PENDING_PAYMENT,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class

In [3]:
optimization_data = df[[
    "order_id",
    "customer_city",
    "customer_state",
    "category_name",
    "product_name",
    "order_item_total",
    "benefit_per_order",
    "days_for_shipping_real",
    "late_delivery_risk",
    "delivery_status",
    "order_status",
    "shipping_mode"
]].copy()

print("Optimization Data Shape:", optimization_data.shape)
optimization_data.head()

Optimization Data Shape: (180519, 12)

,order_id,customer_city,customer_state,category_name,product_name,order_item_total,benefit_per_order,days_for_shipping_real,late_delivery_risk,delivery_status,order_status,shipping_mode
0,77202,Caguas,PR,Sporting Goods,Smart watch,314.64,91.25,3,0,Advance shipping,COMPLETE,Standard Class
1,75939,Caguas,PR,Sporting Goods,Smart watch,311.36,-249.09,5,1,Late delivery,PENDING,Standard Class
2,75938,San Jose,CA,Sporting Goods,Smart watch,309.72,-247.78,4,0,Shipping on time,CLOSED,Standard Class
3,75937,Los Angeles,CA,Sporting Goods,Smart watch,304.81,22.86,3,0,Advance shipping,COMPLETE,Standard Class
4,75936,Caguas,PR,Sporting Goods,Smart watch,298.25,134.21,2,0,Advance shipping,PENDING_PAYMENT,Standard Class

In [4]:
import sys
import os

sys.path.append(os.path.abspath(".."))

from src.optimization.optimize import optimize_orders

In [5]:
selected_orders = optimize_orders(optimization_data)

Status: Optimal
Total Selected Orders: 100

In [6]:
import os

os.makedirs("../reports", exist_ok=True)

selected_orders.to_csv(
    "../reports/optimized_orders.csv",
    index=False
)

print("Optimization results saved in reports folder.")

Optimization results saved in reports folder.

In [7]:
print("========== Optimization Metrics ==========")

print(f"Total Orders in Dataset: {len(optimization_data)}")
print(f"Total Selected Orders: {len(selected_orders)}")

print("\nAverage Shipping Days")
print(f"Before Optimization : {optimization_data['days_for_shipping_real'].mean():.2f}")
print(f"After Optimization  : {selected_orders['days_for_shipping_real'].mean():.2f}")

print("\nAverage Late Delivery Risk")
print(f"Before Optimization : {optimization_data['late_delivery_risk'].mean():.2f}")
print(f"After Optimization  : {selected_orders['late_delivery_risk'].mean():.2f}")

print("\nAverage Benefit Per Order")
print(f"Before Optimization : {optimization_data['benefit_per_order'].mean():.2f}")
print(f"After Optimization  : {selected_orders['benefit_per_order'].mean():.2f}")

========== Optimization Metrics ==========
Total Orders in Dataset: 180519
Total Selected Orders: 100

Average Shipping Days
Before Optimization : 3.50
After Optimization  : 2.03

Average Late Delivery Risk
Before Optimization : 0.55
After Optimization  : 0.00

Average Benefit Per Order
Before Optimization : 21.97
After Optimization  : 486.14